### ISSUE TITLE
Validation errors should appear at location of error

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#112]
In the context of the parameter validation errors, when validation errors occur, it would be nice if the instructions appeared not up at the top, but next to the offending input boxes (before or after). Then at the top, there could be a generic message to "see errors below" and the errors below could be highlighted with a red background highlight. Or something along those lines. (A la standard web form behaviour.) In fact, I'm a bit on the fence about whether to include a message up top at all. I'm thinking ahead to the panel that will hot-modify parameters in the draw view, and there, you don't want the panel to "jump downward" to give an error somewhere up above -- you just want the error to appear next to where the user is playing. But you probably want a top message in the pop-up model we have right now.  This was discussed in PR #108 where Glen said: "That does seem like a good idea, but it would require an extension to the ValidationStatus interface -- basically there would need to be a place to communicate the information of what the offending parameter is. So I think it is actually out of scope for this PR -- it would be great if you can file a separate issue that raises this. Also, I think any solution to this new point will have to resolve #58."

**Comment by gwhitney** [comment]
Planned for beta or later, so putting a beta milestone on this so we can revisit it at that time.

**Comment by gwhitney** [comment]
Actually, we are going to need to expose the sequence & visualizer statuses and their parameter statuses for the sake of fully resolving #113, which is slated for alpha, so bumping this up to alpha.

**Comment by gwhitney** [comment]
Implemented in ui2 per #473. Closing.
