### ISSUE TITLE
Make Prettier Comply With ESLint

### ISSUE THREAD

**Issue by liam-mulhall** [numberscope/frontscope#124]
In https://github.com/numberscope/frontscope/pull/123, I haven't added the package that makes it so that Prettier doesn't clash with ESLint when you have a long line and try to put an operator on the next line. This work was done in https://github.com/numberscope/frontscope/pull/90, but needs to be done again so that we don't have to decorate too much of the code with Prettier directives.

**Comment by gwhitney** [comment]
@liam-mulhall please leave a pointer here to what that needed package is; I will likely work on this sooner than the indeterminate "future."  Thanks!

**Comment by liam-mulhall** [comment]
I believe the (two) packages that need to be added are prettier-eslint and prettier-eslint-cli. This commit https://github.com/numberscope/frontscope/pull/90/commits/ae439ee1962aabddd7c5cec7d2c3524e7bc417b8 might be helpful.

**Comment by liam-mulhall** [comment]
If you want some context for what we were trying to do, start reading from [this comment](https://github.com/numberscope/frontscope/pull/90#issuecomment-1008366630).
