### ISSUE TITLE
visualizer canvas dimensions?

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#125]
Right now the canvas upon which a Visualizer can draw is set at some fixed size, I think 800x800 px. Since for screen media the size of a pixel depends on the recommended viewing distance, I think very few devices on which Numberscope will be viewed even have 800px available in both directions, and some devices have considerably fewer in at least one direction. It's best not to have to scroll to view the full visualizer image, so I'd recommend that we change to an adaptive canvas size, not specified in exact px dimensions, that keeps the full canvas on screen. After all, visualizers already have to deal with making their little BundleCard previews, so they should be able to deal with varying canvas sizes in general. If they specifically want to make a square image, they can just center what they draw on the canvas and use the largest available square subarea. (Alternatively, if we want to move complications out of the visualizers, frontscope could just arrange for the largest visible square canvas and the visualizers could draw on that, so they could always assume the canvas is square. But that would be limiting to those visualizers that can make use of a rectangle, so I wouldn't recommend it.)

**Comment by liammulh** [comment]
[This SO answer](https://stackoverflow.com/a/8486324) might be relevant.

**Comment by gwhitney** [comment]
> [This SO answer](https://stackoverflow.com/a/8486324) might be relevant.

I agree about the relevance of the basic issue that a canvas has two sizes, the nominal "internal" dimensions and the "display" dimensions to which it is stretched. (I wasn't aware of that before, so thanks for posting.) But it seems that the specific code in that solution to deal with the situation isn't quite right, and that certainly the information in one of the comment links, namely

"This is arguably the wrong solution because it's hardcoded and inflexible. [See examples here](http://webglfundamentals.org/webgl/lessons/webgl-anti-patterns.html)"

**Comment by gwhitney** [comment]
Superseded by #277 and #247. Closing.
