### ISSUE TITLE
git hooks allow "non-prettier" code to be committed

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#134]
@gwhitney, suppose you have some poorly formatted changes, you `git add` these changes, and then you try to `git commit`. Right now, I believe the pre-commit hooks are `npm run lint` and `npm run test:unit`. I don't think `npm run lint` can easily fail, so it seems like `npm run lint` runs, succeeds, and then your poorly formatted changes are in version control assuming the tests also succeed. (I don't think the re-formatted files are staged prior to the commit.)

I'll do a bit more investigation tomorrow morning. If what I wrote above is true, then we might want to revert this PR and make some fixes.

_Originally posted by @liam-mulhall in https://github.com/numberscope/frontscope/issues/132#issuecomment-1175784445_

**Comment by gwhitney** [comment]
@liam-mulhall, what is the desired behavior in case a developer asks to commit some files which are not pretter-eslint compliant but which prettier-eslint knows how to fix? (Obviously if there are errors that prettier-eslint cannot fix, then the commit should report them and fail.) Options:

a) The commit fails, the difficulties are reported, but no source files are changed. The developer would presumably respond by executing `npm run lint`, perhaps examining the results (although we are basically defining the output of prettier-eslint when the result has no eslint errors as being "correct", so what is there to check?) and the redoing the commit.

b) The commit fails but the offending source files have been automagically changed, just as when the developer does `npm run lint` directly. The developer would presumably respond by possibly looking at the fixes (again, doesn't seem worthwhile) and re-issuing the commit.

c) The offending source files are reported and fixed, added to the staged changes, and the commit proceeds normally.

d) something else?

My vote is for (c) as in options (a) and (b) it seems we pretty much doom the developer to automatic responses leading to just reissuing the commit. (and in fact, I assumed (c) was what was happening, and I didn't realize that prettier-eslint suppresses eslint errors it can't fix :( ... ) But let me know your thoughts; I won't submit a PR for this until there's a decided course of action. @katestange we would value your perspective as well.

**Comment by gwhitney** [comment]
Note that if we do want (c) from the prior post, we need to use a tool that will only run prettier-eslint on the staged files and then add any changes it makes to the previously-staged changes. As far as I can tell, that means either (i) installing https://github.com/okonet/lint-staged, resulting in a somewhat roundabout hook structure (husky is configured to call lint-staged which in turn is configured to call the commands you actually want to run), or (ii) switching from husky to https://github.com/evilmartians/lefthook which is a more general solution for git hooks that includes all of the functionality of husky and lint-staged and replaces husky's configuration directory with a single YAML file, at the cost of using a Go-language binary which is supposedly autodownloaded for the proper architecture at install time. So I'd be happy to have any thoughts about which way to go (leaning very slightly toward option (i) as installation seems more straightforward even though the resulting setup seems slightly more convoluted; but I would be fine either way).

**Comment by gwhitney** [comment]
A final note before I sleep on this: if we go with option (c) via lint-staged or lefthook, when you do a commit only the changed files are examined, as opposed to `npm run lint` which looks at the whole repository. That's good in that it's noticeably faster, but on the flip side, if any lint problems do somehow slip into the repository, committing a change to other files won't detect the problem. This difference should be fairly moot once this infrastructure is all in place, since then how would any lint problems ever make it into the repository? And we can always recheck the whole repository with an explicit `npm run lint`. So I think there are no worries, I just thought I should mention.

**Comment by liam-mulhall** [comment]
Let me see if I understand (c). In (c), if a dev has poorly formatted files and they `git add` and `git commit` them, then there will be command line output:

* of the Prettier and/or ESLint errors,
* indicating that prettier-eslint has automagically fixed their errors,
* indicating these fixes have been staged for the current commit

Is that correct?

**Comment by gwhitney** [comment]
That would be a (d), a close variant of (c). The (c) I was proposing would list the files prettier-eslint changed, and then would report that there were no further errors. The fact that additional changes to the listed files were staged would be implicit. I could make it work like the (d) you propose *except* I don't think there is any concept of a "prettier error" - it just makes changes or not, I don't think it has a mode where it reports why it wants to change. So I could report eslint errors, then a list of changed files added to the staging, then a confirmation of no more eslint errors. But **note** prettier sometimes makes changes when there are no eslint errors -- for example there are line breaks in multi-line formulas that eslint thinks are totally fine, like
```
a = 2
    + 2
```
that prettier modifies, in this case putting it all on one line. But I don't think we can get prettier to say "dude you had way too short a line" ;-)

**Comment by liam-mulhall** [comment]
Okay, I think I understand (c) now. Thanks.

> The fact that additional changes to the listed files were staged would be implicit.

I guess I'm fine with (c) as is. It seems a bit magical, but I think that's going to be fine 99% of the time. The only scenario I can think of where it wouldn't be fine is if a student or contributor had some non-compliant code that they want formatted in a certain way (maybe they have a large array of values or something) and they commit it, and then scratch their heads wondering how it got re-formatted. But it seems like the solution in that scenario would be to add another commit that ignores either Prettier or ESLint and re-formats.
