### ISSUE TITLE
`npm install` doesn't work on Windows.

### ISSUE THREAD

**Issue by Decos14** [numberscope/frontscope#149]
The commands in the existing build and postinstall scripts don't work on Windows.

Liam and I modified the build and postinstall scripts on my machine:

```json
"build": "npm run typecheck && vite build && .\\.venv\\Scripts\\mkdocs.exe build",
"postinstall": "python -m virtualenv .venv && .\\.venv\\Scripts\\activate && pip install -r requirements.txt",
```

**Comment by gwhitney** [comment]
Hmm, but I assume those backslashes will not work on unix variants (Linux/MacOS/etc.) So we could not just check those changes into main. Is there a notation npm understands that means `/` on Unix and `\` on Windows? Or some other OS-invariant way to refer to and execute programs from subdirectories? (Frankly I had just assumed npm would be "smart enough" to translate `/` to `\` on Windows...)

**Comment by liammulh** [comment]
No, we can't check it in to main. I'll search around and try to find a solution.

I just wanted to document the problem and our workaround.

@Decos14 is now able to work on a "Hello, World" visualizer.

**Comment by gwhitney** [comment]
I believe https://www.npmjs.com/package/nopy will do the trick for us. I will try it out tomorrow and file a PR if so.

**Comment by gwhitney** [comment]
Actually, that's not going to work. The `nopy` relies exclusively on package.json and #147 is going to eliminate package.json. Also, the venv is working fine, it's just a matter of finding an OS-indpendent way to invoke programs in the venv, which doesn't really have anything to do with python per se. There is another package `run-script-os` that just allows you to specify OS-dependent versions of scripts, but it only works with npm and yarn. So I will continue to seek a simple solution for invoking mkdocs.

**Comment by liammulh** [comment]
We could write a JavaScript (or Python) script that basically does something along the lines of:

```
if os is unix-like:
  execute these commands
else if os is dos-like:
  execute these commands
```

And then in the build and postinstall scripts we do:

`node myScript.js`

or

`python3 my_script.py`.

**Comment by gwhitney** [comment]
yes am doing exactly that (was more convenient in node). Should have a PR in an hour or so.
