### ISSUE TITLE
Bug: OEIS sequence does not work if no modulus is specified

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#15]
To reproduce, get a server running per the instructions in backscope, and then run the frontscope. Click "get started," then "Get Sequence". Enter A000045 for the sequence number, whatever name you like, 50 entries (to keep things simple), and a modulus of 1000. Select the resulting sequence, and the difference visualizer with the default settings. Create the bundle, and draw. Make sure that initial values of the sum recurrence are displayed.

Now repeat the process with no modulus specified, and draw the resulting difference visualizer. The row that should display the sequence will be blank, and all differences will be NaN.

**Comment by liam-mulhall** [comment]
I was able to reproduce the issue following the steps outlined above.
