### ISSUE TITLE
Make "Intro to working with BigInts" document

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#163]
Transitioning from JavaScript's Number type to BigInts is a bit painful, and it would help to make a document that provides an introduction to working with BigInts.

- Related: We should also note that JavaScript's mod is different from the actual mathematician's mod. See also https://github.com/numberscope/frontscope/issues/48.

**Comment by gwhitney** [comment]
Oops, another:
7) bigint division automatically "floors" the result. So for example `3n/5n` is `0n`. Be careful to think if that's what you want; if not you may need to rearrange your expressions. For example `x * (3n/5n)` is very different from `(x*3n)/5n` -- the former is always 0n, the second will have the value 60n, for example, when x is 100n.

**Comment by liammulh** [comment]
> You should always try to avoid converting a bigint into a JavaScript number. If you find yourself forced into doing this, you should worry about overflow, and check for it unless you're absolutely certain overflow can't happen in that particular conversion. But note that any number you get from the OEIS might overflow JavaScript number.

Maybe we can create a utility function that helps check for overflow?

**Comment by liammulh** [comment]
> Use triple-equal === to check if two bigints are the same and !== to check they are different.

Perhaps we could explain the difference between ==, != and ===, !==. Or maybe that is outside the scope of this doc?

**Comment by gwhitney** [comment]
> > Use triple-equal === to check if two bigints are the same and !== to check they are different.
> 
> Perhaps we could explain the difference between ==, != and ===, !==. Or maybe that is outside the scope of this doc?

I think it is. The fact is that for bigints there is never any reason to use == or !=, so it's easy to just say only use === and !==. But going into the exact difference between == and === is a bit of a can of worms that's not directly relevant to bigints, I think...

**Comment by gwhitney** [comment]
> > You should always try to avoid converting a bigint into a JavaScript number. If you find yourself forced into doing this, you should worry about overflow, and check for it unless you're absolutely certain overflow can't happen in that particular conversion. But note that any number you get from the OEIS might overflow JavaScript number.
> 
> Maybe we can create a utility function that helps check for overflow?

Good idea, doing that in my math PR
