### ISSUE TITLE
Differences visualizer does not work with OEIS sequences

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#17]
To reproduce: With a running backend and frontend, go to the scope on frontend. Add any (working) OEIS sequence with the "Get Sequence" button, such as A000045 with 50 terms and modulus 1000. Bundle that with the Differences visualizer, and then click "Draw." The sequence values will display along the top of the page, but no differences will be shown.

On the other hand, if you bundle the "Naturals" sequence with the Differences visualizer, the differences are properly shown.

**Comment by liam-mulhall** [comment]
Able to reproduce following above steps.
