### ISSUE TITLE
Update PR checklist once new tests are added

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#174]
From https://github.com/numberscope/frontscope/pull/171#discussion_r998382146. Once new tests are added, we'll need to update the PR checklist doc.

**Comment by gwhitney** [comment]
I think this issue needs more specifics, but is likely still a thing.

**Comment by gwhitney** [comment]
This should be folded into #420.

**Comment by gwhitney** [comment]
Resolved in ui2 thanks to #420. Closing.
