### ISSUE TITLE
p5 createGraphics buffer cleared when the draw button is pressed.

### ISSUE THREAD

**Issue by Decos14** [numberscope/frontscope#175]
My visualizer uses the [createGraphics()](https://p5js.org/reference/#/p5/createGraphics) function from p5. However when the draw button is pressed, anything in the off-screen buffer clears, but the draw loop doesn't restart. So it only draws things from after when the draw button is pressed.

**Comment by liammulh** [comment]
@Decos14, do you re-initialize the state of your visualizer's variables in the p5 `setup()` function?

**Comment by gwhitney** [comment]
Assuming this is moot. Closing.
