### ISSUE TITLE
Factor Histogram Visualizer: add scale to y-axis

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#220]
The histogram can be a bit tricky to interpret as no scale is shown on the y-axis. Such a scale should be given and/or there should be a way to see the count of values in each bin.

**Comment by Decos14** [comment]
I was planning on adding that along with a mouse over feature. If you like I could take this issue and it should be finished in about a week in a half to two after finals are over.

**Comment by gwhitney** [comment]
You are welcome to take on this issue at any point. The protocol is that at such point as you start active work on it, you assign yourself to the issue, under "Assignees" at the top right. (If you don't see an "assign yourself" button there, just put a comment here in the discussion that you are working on it, and one of the maintainers will assign you.) Assigning yourself is an informal commitment that you will see it through to a PR. And if anyone else should happen to start work on this in the meantime, they would assign themselves. That way, we don't end up with either duplicated work by two people working on the same issue or an "orphaned" issue that someone was working on but got stalled. Thanks!

**Comment by Decos14** [comment]
I can't assign it to myself. But I will take care of it.

**Comment by gwhitney** [comment]
OK, it's assigned to you. So nobody else will work on this until either you file a PR or let us all know that you're not going to be able to complete the issue. Thanks for your efforts!

**Comment by Decos14** [comment]
Hi, I just submitted the pull request for this issue. However I don't have access to be able to link it to this issue.

**Comment by gwhitney** [comment]
All you need to do for that is just put the phrase "Resolves #NNN" on a line by itself in the description of a PR, and it auto-links. (I have just done that for your PR.) Thanks for filing, we'll take a look!
