### ISSUE TITLE
Update or Delete Dependencies

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#24]
The frontend has many dependencies that are outdated. See below for what `npm outdated` yields.

<details>
<Summary>Outdated Dependencies</Summary>

| Package                          | Current    | Wanted | Latest | Location                                      | Depended by |
|----------------------------------|------------|--------|--------|-----------------------------------------------|-------------|
| @types/p5                        | 0.9.0      | 0.9.1  | 1.3.1  | node_modules/@types/p5                        | frontscope  |
| @typescript-eslint/eslint-plugin | 2.27.0     | 2.34.0 | 4.33.0 | node_modules/@typescript-eslint/eslint-plugin | frontscope  |
| @typescript-eslint/parser        | 2.27.0     | 2.34.0 | 4.33.0 | node_modules/@typescript-eslint/parser        | frontscope  |
| @vue/cli-plugin-babel            | 4.3.1      | 4.3.1  | 4.5.13 | node_modules/@vue/cli-plugin-babel            | frontscope  |
| @vue/cli-plugin-eslint           | 4.3.1      | 4.3.1  | 4.5.13 | node_modules/@vue/cli-plugin-eslint           | frontscope  |
| @vue/cli-plugin-router           | 4.3.1      | 4.5.13 | 4.5.13 | node_modules/@vue/cli-plugin-router           | frontscope  |
| @vue/cli-plugin-typescript       | 4.3.1      | 4.3.1  | 4.5.13 | node_modules/@vue/cli-plugin-typescript       | frontscope  |
| @vue/cli-service                 | 4.3.1      | 4.3.1  | 4.5.13 | node_modules/@vue/cli-service                 | frontscope  |
| @vue/eslint-config-typescript    | 5.0.2      | 5.1.0  | 7.0.0  | node_modules/@vue/eslint-config-typescript    | frontscope  |
| axios                            | 0.21.1     | 0.21.4 | 0.22.0 | node_modules/axios                            | frontscope  |
| core-js                          | 3.6.5      | 3.18.2 | 3.18.2 | node_modules/core-js                          | frontscope  |
| css-loader                       | 3.5.2      | 3.6.0  | 6.3.0  | node_modules/css-loader                       | frontscope  |
| eslint                           | 6.8.0      | 6.8.0  | 7.32.0 | node_modules/eslint                           | frontscope  |
| eslint-plugin-vue                | 6.2.2      | 6.2.2  | 7.19.1 | node_modules/eslint-plugin-vue                | frontscope  |
| jquery                           | 3.5.0      | 3.6.0  | 3.6.0  | node_modules/jquery                           | frontscope  |
| p5                               | 1.0.0      | 1.4.0  | 1.4.0  | node_modules/p5                               | frontscope  |
| typescript                       | 3.8.3      | 3.8.3  | 4.4.3  | node_modules/typescript                       | frontscope  |
| vue                              | 2.6.11     | 2.6.14 | 2.6.14 | node_modules/vue                              | frontscope  |
| vue-js-modal                     | 2.0.0-rc.3 | 2.0.1  | 2.0.1  | node_modules/vue-js-modal                     | frontscope  |
| vue-loader                       | 15.9.1     | 15.9.8 | 15.9.8 | node_modules/vue-loader                       | frontscope  |
| vue-router                       | 3.1.6      | 3.5.2  | 3.5.2  | node_modules/vue-router                       | frontscope  |
| vue-template-compiler            | 2.6.11     | 2.6.14 | 2.6.14 | node_modules/vue-template-compiler            | frontscope  |
| vue-unique-id                    | 3.1.0      | 3.2.1  | 3.2.1  | node_modules/vue-unique-id                    | frontscope  |
| vue-template-compiler            | 2.6.11     | 2.6.14 | 2.6.14 | node_modules/vue-template-compiler            | frontscope  |
| vue-unique-id                    | 3.1.0      | 3.2.1  | 3.2.1  | node_modules/vue-unique-id                    | frontscope  |

</details>

We should try to update dependencies that can be updated and delete dependencies that can be deleted.

**Comment by gwhitney** [comment]
`npm outdated` now returns much less, but not nothing, so I guess this issue still requires further work.

**Comment by gwhitney** [comment]
The issue statement suggests that we delete dependencies that can be delete. Do you think there currently are any? `npm prune --dry-run` doesn't report any packages it would prune, but maybe there could be items listed in package-json that we don't really need. Is that the concern? How would you suggest that we go about finding any, if they exist?

**Comment by gwhitney** [comment]
A separate question: dependencies go out of date all the time. I see that backscope has dependabot set up, but it doesn't seem like this repository does. Do you know how to set it up? I never have... Should it be considered within the scope of this issue that once all dependencies are up to date (or deleted, see previous question) that dependabot be initiated to try to keep things that way?

**Comment by gwhitney** [comment]
OK as discusssed today we should have a dependabot.yml to set that up

**Comment by liam-mulhall** [comment]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

**Comment by liam-mulhall** [comment]
> run npx depcheck in the project root directory

See https://stackoverflow.com/a/27362322.
