### ISSUE TITLE
Two canvases are being drawn for each bundle card

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#244]
When writing an E2E test, I noticed something interesting:

<img width="800" alt="two-canvases" src="https://user-images.githubusercontent.com/60749003/211881748-9cc96ddc-27b1-428b-856f-f50f80fbb8d5.png">

Seemingly there are two canvases on the bundle card page. There's a canvas in the lower left corner with ID `defaultCanvas0` and there's a second one in the bundle card with ID `defaultCanvas1`.

What I think is happening is that when you select a sequence and a visualizer, the first canvas with ID `defaultCanvas0` is being drawn, and then when you click the "Create Bundle" button, the second canvas with ID `defaultCanvas1` is being drawn. You can verify this by using the developer tools console and typing something like `document.querySelectorAll('canvas')`.

So I think we need to figure out why the initial canvas is being drawn. It isn't necessary.

**Comment by liammulh** [comment]
I wonder if `defaultCanvas0` is being drawn because in `VisualizerDefault` we initialize the `sketch` variable with a dummy p5 instance?

https://github.com/numberscope/frontscope/blob/de1ded572b722db07d5b1e9b70a02bc84648174a/src/visualizers/VisualizerDefault.ts#L7-L16

**Comment by gwhitney** [comment]
This symptom is gone in main in both dev mode and in the built frontscope, presumably because of #277. Closing.
