### ISSUE TITLE
Variation on chaos visualizer

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#248]
This is a slight variation on the chaos game:  it would be easy to set the chaos visualizer to allow such an option:

https://twitter.com/matthen2/status/1268808515574886407

**Comment by katestange** [comment]
On the Illustrating Mathematics discord server, user peteok did this with a square using various types of triangle centres from [Clark Kimberling's Encyclopedia of Triangle Centers](https://faculty.evansville.edu/ck6/encyclopedia/etc.html) and it produced very interesting and beautiful results!

**Comment by gwhitney** [comment]
Indeed, and if we wanted to allow the choice of various centers, I think this might be meaty enough for its own visualizer rather than shoehorning it into the existing chaos visualizer...

**Comment by gwhitney** [comment]
Moved into the visualizer ideas discussion; closing.
