### ISSUE TITLE
Trouble Importing Files

### ISSUE THREAD

**Issue by liam-mulhall** [numberscope/frontscope#29]
In a discussion on Slack, I asked:

> Has anyone else experienced an issue where imports using `@`  don't work? From what I understand, the `@` is basically an alias for the src directory. I don't see where this alias is set. Any ideas?

@samzhang111 pointed out that this alias is set in `tsconfig.json`. @gwhitney pointed out that this might be an issue with loaders or shims rather than the `@` alias.

Glen was able to fix the problem he was having by adding the `.vue` file extension to his import.

**Comment by liam-mulhall** [comment]
In https://github.com/liam-mulhall/frontscope/commit/02a2937cf85feabf3ed6b3ffbbd706d95964b23c, I was trying to write a non-trivial test, but got stuck because of this issue.

# Steps to Reproduce

1. Clone git@github.com:liam-mulhall/frontscope.git.
2. `git checkout set-up-jest`.
3. `npm test`.

`npm test` should yield the following.

```sh
 FAIL  src/visualizers/VisualizerDefault.unit.test.ts
  ● Test suite failed to run

    Cannot find module '@/visualizers/VisualizerDefault' from 'src/visualizers/VisualizerDefault.unit.test.ts'

    > 1 | import {VisualizerDefault} from '@/visualizers/VisualizerDefault';
        | ^
      2 |
      3 | jest.mock( './VisualizerDefault' );
      4 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:322:11)
      at Object.<anonymous> (src/visualizers/VisualizerDefault.unit.test.ts:1:1)
```

**Comment by gwhitney** [comment]
Great, thanks. If I don't see any report of progress here by tomorrow, I will take a crack at this (just waiting in case you are still working on this today).

**Comment by gwhitney** [comment]
The difficulty is that jest uses its own resolver, not TypeScript's. Hence, you need to run `jest --init` in your branch, which will ask you some questions and then create a jest.config file (either `jest.config.js` or `jest.config.ts` depending on how you answer the questions, but I presume the latter) and then look for the section:
```
  // A map from regular expressions to module names or to arrays of module names that allow to stub out resources with a single module
  // moduleNameMapper: {},
```
and uncomment the second line and change it to
```
  moduleNameMapper: {'@/(.*)' : '<rootDir>/src/$1', },
```
and then you should be good to go. Let me know if this works for you.

**Comment by liam-mulhall** [comment]
This isn't an issue anymore. Closing.
