### ISSUE TITLE
Remove "Sequence Playground" from UI?

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#33]
At a group meeting a couple of weeks ago, the consensus seemed to be that this was sort of a prototype to see if the front end could read sequences before there were visualizers to look at them with. So probably this section of the UI, which doesn't really seem to add any functionality, should seemly be retired and removed. But this should be explicitly agreed upon by the group before proceeding.

**Comment by liam-mulhall** [comment]
I think it might make sense to discuss "The Scope" and "Specimens" in separate issues. "The Scope" seems vague to me. I'm not sure what that link would lead to. I have no idea what "Specimens" is supposed to be.

**Comment by liam-mulhall** [comment]
See #79 and #78.
