### ISSUE TITLE
Delete individual sequences in favor OEIS formula sequence class

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#34]
With the resolution of #14, the "constant" and "natural numbers" sequences are, from a pure capability standpoint, redundant since they can easily be produced by simple formulas. This issue is filed simply as a placeholder that at some point there needs to be a decision as to whether to leave these simple sequences in the interface, or take them out to save the screen real estate since you can obtain their behavior another way.

**Comment by liam-mulhall** [comment]
GW: "Once we have sequence identifiers (A######), we won't really need different sequence names generally."

**Comment by liam-mulhall** [comment]
We should get rid of all individual sequences once we have the OEIS formula sequence class (or whatever we end up calling it) in place.

**Comment by gwhitney** [comment]
Depends on #23. (Is there some more formal place to put such info rather than just in the text of a comment?)

**Comment by gwhitney** [comment]
We are no longer planning to remove different sequence types altogether because of the use case of sequences uploaded by the visualization creator. But we do have naturals slated for replacement by a "canned" Formula instance. And we do plan to allow OEIS names in formulas. So closing this issue.
