### ISSUE TITLE
Mouse over gallery specimens

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#373]
Currently we see a mouse arrow, not pointer (index finger), when hovering over gallery specimens, which are clickable.  Do we want to change this?  The reason is that the canvas controls the pointer behaviour.  See discussion [here](https://github.com/numberscope/frontscope/pull/368#discussion_r1660313949).

**Comment by gwhitney** [comment]
Actually it turns out _we_ were overriding the pointer behavior, so I believe this is moot. Closing.
