### ISSUE TITLE
Should Turtle pause when it has wandered far away? Or draggable viewport?

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#381]
It's fairly easy to set up a Turtle that runs offscreen and spends lots of time far from the origin, but keeps using processor power etc. as it "draws" this invisible part of the turtle's path. Of course, sometime the turtle can return from afar, but often it doesn't. Would it be worth it to make Turtle watch itself and if it spends some large number of turns outside the visible area, it pauses itself (noloops) to stop burning processor cycles? If #380 is addressed in some way, this could still allow the person doing the visualization to click play to continue further if they want to, to see if it comes back.

As an alternative, or in addition, it could be cool to have the viewport of the Turtle be draggable, so you could drag the whole image around and "find" the Turtle and watch whatever it's doing now. That sounds like a bunch more work, but cooler and more fun in the end. I guess the ultimate version of this would also allow zooming the whole picture in or out in some way, without disrupting what's already been drawn or the current action of the turtle. That might well need to depend on a switch to the svg version of p5 to be feasible.

**Comment by katestange** [comment]
Another possible idea (in combination or instead) is to let the turtle visualizer adjust itself (zoom/pan) to keep the turtle in view.

**Comment by katestange** [comment]
Also the turtle should allow zooming.

**Comment by gwhitney** [comment]
And it should allow a speed parameter (number of steps to take per frame)

**Comment by gwhitney** [comment]
These items should be considered, but optional, for the Turtle overhaul in progress for alpha. So not adding a milestone to this issue.

**Comment by gwhitney** [comment]
Everything in here is now implemented or re-listed in #471, so closing.
