### ISSUE TITLE
State Isn't Saved If You Refresh Page

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#39]
Not a pressing issue, but something we'll eventually want to sort out.

# Steps to Reproduce

1. Run the frontscope development server. (Run it locally.)
2. Click the "Get Started!" button.
3. Add natural numbers.
4. Add differences.
5. Create bundle.
6. Refresh the page.

You will no longer have your natural numbers + differences bundle.

# Solution(s)

* Defining new routes and using Vue Router's `router` methods might help.
* We might need/want to store state client-side. That is, we might need/want to store state in browser local storage. @gwhitney suggested following [this tutorial](https://dev.to/nickitax/persistent-store-with-vuejs-vuex-and-vuex-persisted-state-354n) to do so.

**Comment by gwhitney** [comment]
Another potentially instructive example of a graphical Vue app that keeps state across page reloads, without using the whole vuex mechanism, is https://konvajs.org/docs/vue/Save-Load.html (note however that it's a different graphics library, not p5, and it's Vue 2.x, not Vue 3; but I think the basic ideas are still valid, although not 100% certain).

**Comment by khaledallen** [comment]
This might be somewhat connected to #83. Saving state for exporting might be useful for saving state internally as well.

**Comment by gwhitney** [comment]
resolved in ui2. Closing.
