### ISSUE TITLE
Abstract visualizers away from being tied specifically to p5

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#41]
We envision that there may be network visualizers and/or table visualizers and/or ... that will want to use other rendering libraries besides p5. Right now, the VisualizerInterface explicitly supposes that there will be a p5 sketch associated with the visualizer. It should be divided into a generic interface that is agnostic about what is doing the rendering, and a specialized P5VisualizerInterface that extends the generic one and assumes there's a p5 sketch, so that other sorts of visualizers can be introduced into the hierarchy.

**Comment by gwhitney** [comment]
Example libraries that one might want to use for visualiazation: three.js to produce 3D graphics; vis.js for networks and other data structures, including possibly "ordinary" graphs of sequence values; and/or bootstrap-table for tabular data (and quite possibly VisualizerDifference should really be done with a table library rather than p5).

**Comment by liam-mulhall** [comment]
See https://github.com/numberscope/frontscope/issues/120#issuecomment-1194525172 for how we will proceed.
