### ISSUE TITLE
Inconsistent numeric types in certain sequences

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#42]
The SequenceInterface says that getElement returns "number," but on the other hand, OEISSequenceTemplate fills the cache which produces values for getElement with "BigInt"s. (I am not sure what TypeScript's exact typing rules are for numbers here, so I am unclear on why TypeScript does not report any type error or warning for the code that puts BigInts into a cache declared to contain numbers.)

Anyhow, this mismatch causes some visualizers, e.g. ShiftCompare, to fail on OEIS sequences; they contain code that performs computations (such as the modulo operator) which does not allow mixing of BigInts and numbers.

We need to decide on a policy of how to represent numbers for sequences in Numberscope, and then use it uniformly.

**Comment by katestange** [comment]
Yes, we should probably discuss this on Friday.  I feel strongly that we should support BigInts, or we will be hobbled (the integers in the OEIS are just big).  But it opens a lot of questions about how to require visualizers to behave.

**Comment by gwhitney** [comment]
I guess there is also the question of the numeric type for the input to getElement, i.e. of the index for a sequence. Plain old "number" seems adequate for that, since we generally only analyze thousands of terms in a sequence,, so maybe we should just leave it be as "number". Unless it seems logically simpler/more consistent to map BigInts to BigInts...

**Comment by gwhitney** [comment]
We had a productive conversation about this at the meeting today. To summarize the consensus approach:


1. Sequence objects will handle only integers. 
2. More specifically, Sequence objects might need to do non-integer calculations internally, and a client like a Visualizer might want to do non-integer calculations with the results, but the interfaces will only be in terms of those integers.
3. To handle the full spectrum of the OEIS, those integers require arbitrary precision.
4. Hence, all of the Sequence interfaces will be modified to operate in terms of the javascript BigInt datatype, both for input and output (because not infrequently one wants to combine indices and sequence elements in some way).
5. However, in recognition of point (2.) and the desire to make Visualizer writing as easy as possible, Numberscope will have to provide ways to perform at least common non-integer operations on BigInts, such as sin, cosine, natural log, fractional/negative powers, and probably more. We want these all to be as painless to a Visualizer writer as possible, so ideally the standard context or imports for writing a Visualizer provides the necessary operations (and fails in a very clear way when the operation is not available). Similarly, to make things as easy as possible for creating sequences, we want to make bigint as close to a "native" type for math.js as well.
6. In pursuing (5.) we should strive to re-use as opposed to re-invent as many wheels as possible. Notably Sage has already solved all of the mathematical problems implicit in (5.)
7. Finally, the implementations should recognize that computational issues exist also for operations that are strictly integer-to-integer. For example,we would like to make `(a**k) % n` for a, k, and n being BigInts automagically avoid doing the stupid thing of calculating a**k exactly and then modding by n, but rather use an algorithm that frequently mods out by n en route. Ideally, this would automatically happen in ordinary arithmetic expressions both in TypeScript Visualizer code and in math.js expressions. That may turn out to be unrealistic in one or both of these contexts, in which case we would probably have to settle for providing a `powmod(a,k,n)` function for that context and prominently advertising it for people to use. There are probably other similar cases, although this is likely the most critical one.

If you have any comments/edits on this plan, please do post them as soon as you have the opportunity. I can commence work on this as soon as my last PR is cleared.

**Comment by gwhitney** [comment]
And I guess somewhere in the "user guide," we likely will want a "visualizer writer's guide" with some information about doing calculations with the output of Sequence objects. Should an issue for this be created now, or when we have a clearer idea about what all that would comprise?

**Comment by liam-mulhall** [comment]
> Should an issue for this be created now, or when we have a clearer idea about what all that would comprise?

I vote for a placeholder issue.

**Comment by gwhitney** [comment]
In practice, point (4) in the resolution turned out to just seem wrong; we far more often use the input to a sequence just as an index and don't combine it with the results. The code will look much more "normal" if we leave this as an ordinary typescript number. So hereby reversing course on that point.

**Comment by gwhitney** [comment]
In the first rendition of this (#50), in order to have a way to indicate that an index was not valid for a given Sequence, I had to make the return type of getElement be `bigint|undefined`. This however will complicate computing with the output of a Sequence. So there is an alternative proposal in which a Sequence would have methods providing the range of valid indices and getElement would always return a `bigint`. Resolving this can't proceed until we decide between these alternatives, so please see the discussion on them in #48 and provide your thoughts/votes. Thanks!

**Comment by gwhitney** [comment]
"Proposal B" in the discussion of #48 has been adopted, so when PR #51 is finally merged, it will resolve this issue.
