### ISSUE TITLE
Some formula entry impractical in ui2

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#427]
Right now when entering a formula, if you want to change from `permutations(n,3)` to `combinations(n,3)` (say), and you do this by deleting `permut` character-by-character and then typing `combin`, you get an error dialog that e.g. `permations` is an undefined function for every single keystroke that you have to respond to by clicking on an 'OK' button. It is frustrating and makes formulas essentially unusable. We need to make the validation of formulas "softer" in some way for the instant update to be usable.

_Originally posted by @gwhitney in https://github.com/numberscope/admin/discussions/6#discussioncomment-9899148_

**Comment by katestange** [comment]
This behaves as described and fixes that problem.  But I got a popup that permutations requires second argument to be less than first argument.  There are still going to be tons of popups as we use this.  Is it possible to route _all_ popups that derive from mathjs to a red error message like this PR does for unknown function?

**Comment by gwhitney** [comment]
Formula entry much smoother in ui2 thanks to #498, closing.
