### ISSUE TITLE
Don't `console.log` in Production

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#45]
It's generally considered bad practice to use `console.log` in production. When we deploy, we need to make sure we don't have any `console.log`'s.

It might be that `npm run build` strips out `console.log`'s. We can address this when we're close to deploy.

**Comment by gwhitney** [comment]
I recommend this issue remain until, and be closed when, there are no console.log commands anywhere in the code base that could be hit in production operation. (I am not actually clear on how far or near we are to that state.)
