### ISSUE TITLE
Potential Visualizer writers need easily accessible guidance

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#46]
This is mainly a placeholder for the fact that ultimately the "user's guide" will need to include a section on writing/deploying a new Visualizer. In particular, this will need to address whether and how it's possible to do that independently of running from a modified clone of the full frontscope source.

**Comment by gwhitney** [comment]
Also as noted in #42, this guidance likely will also need to comment on how best to manipulate the output of Sequences numerically, especially if non-integer functions like sine or log need to be applied.

**Comment by katestange** [comment]
There is some of this in README.md, to be expanded.

**Comment by gwhitney** [comment]
> There is some of this in README.md, to be expanded.

True, but one of the intentions of this issue is to make this sort of information accessible through the Numberscope site, in conjunction with the other "User's Guide" information that is already available that way.

**Comment by katestange** [comment]
A note for eventual inclusion in visualization documentation:  I ran across the issue that p5 colours can't be defined outside setup() and draw().  With typescript, this requires some workaround for your colour variables.  See here: https://chrome.google.com/webstore/detail/super-dark-mode/nlgphodeccebbcnkgmokeegopgpnjfkc?hl=en

**Comment by gwhitney** [comment]
Hmm, following that link got me basically to an ad for Super Dark Mode; I couldn't see anything about p5... Maybe you could cut and paste the relevant information into this conversation?

**Comment by katestange** [comment]
Sorry, my brain isn't 100% -- link fixed.

**Comment by katestange** [comment]
Another small thing to make sure is included in these docs:  when the canvas is resized and it starts over (e.g. in the current setup when going from a "card thumbnail" to the full viz and back), the code runs setup() again without first cleaning up; so make sure setup() cleans up anything you've been doing in draw().  (I ran into bugs from not realizing this and not cleaning out an array.)

**Comment by liam-mulhall** [comment]
Related to https://github.com/numberscope/frontscope/issues/127.

**Comment by liammulh** [comment]
I'm not working on this right now. Unassigning myself.

**Comment by gwhitney** [comment]
#293 is relevant, but I doubt will be comprehensive to all of the aspects brainstormed in this issue, so there will likely be a remnant of this issue to be left open even after that lands.

**Comment by gwhitney** [comment]
We are close to resolving this, so should just be finished off with doc overhaul for alpha.

**Comment by gwhitney** [comment]
> this will need to address whether and how it's possible to do that independently of running from a modified clone of the full frontscope source

Moved this point to #489 for the sake of being able to resolve this in hopefully under three years from its creation (gosh, have I been collaborating on Numberscope that long??!)

**Comment by gwhitney** [comment]
There are only two points remaining in this issue:

* Guidance on how to use non-integer-valued functions (like sine or exp) in computing with sequence values
* How/when one can initialize p5 Color variables and the use of INVALID_COLOR as a TypeScript workaround.

I could use some guidance/suggestions as to where to put this information in the documentation, especially with the "Building a Visualizer" page already so long. If we adopt the [suggestion from a discussion] of having an "intermediate" visualizer-writing page, I think they could both go there. But maybe there's a better way to split the information currently in "Building a visualizer" together with these points?

**Comment by gwhitney** [comment]
All of these items are in ui2 per #486, so closing.
