### ISSUE TITLE
Add prototype chaos visualizer

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#47]
Kate wrote various standalone visualizers outside the numberscope (https://math.katestange.net/numberscope/).  The chaos visualizer is not computationally intensive (no factoring etc), and fairly simple (not too much code), so this is a good first choice to try to port into Numberscope.  Note:  a particularly beautiful implementation of the pure chaos game (not based on an arbitrary sequence) is available at (https://experiments.withgoogle.com/the-chaos-game).

**Comment by gwhitney** [comment]
Nice! This suggests to me these question: is there an overall project goal of at some point incorporating all of the visualizers on that numberscope page you link above? More specifically, is there an intention to replace the current ShiftCompare visualizer with the Self-Similarity visualizer?

**Comment by katestange** [comment]
Yes, I think so, if they are up to snuff.  But the user interface will probably change (right now I coded a pop-up menu into each visualizer, etc.), so they'll be changed as they are incorporated.

**Comment by gwhitney** [comment]
OK, then I'd recommend when you have a chance filing a placeholder issue for porting other standalone visualizers to Numberscope, that could in the fullness of time be replaced by a series of issues, one for each visualizer that should be incorporated; and the one for Self-Similarity would make it clear if it replaces ShiftCompare.
