### ISSUE TITLE
bug: sequence index popup error should be part of error/warn system

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#476]
Go to this url:
http://localhost:5173/?name=ModFill&viz=ModFill&modDimension=200&seq=Formula&formula=n%21
And then try to make the index negative.  Type - in the sequence index box and an appropriate error is displayed.  Follow that up by typing 1 (so it should show -1), and instead we get a popup error message, as follows:
![Screenshot from 2024-10-26 15-11-31](https://github.com/user-attachments/assets/21ddd80f-c2dc-4aa5-a479-8f64a6b4bfbf)
I think that such an error ought to be part of the error/warn system, not a show-stopping pop-up.  But note that it's important we are using the formula n! to cause this -- it appears to come from math.js or somewhere, because using a formula like n doesn't have this behaviour.  So maybe this is about handling mathjs complaints better?

**Comment by gwhitney** [comment]
Yup, this is all about mathjs. I don't think there's any possible way we can detect what combinations of formulas and indices will cause mathjs to throw errors. So this is not a parameter validation problem. Hence it is not a "bug" per se; all error-throwing is handled by these pop-ups. In other words, the designed behavior is occurring. Hence, I am changing the label to UI and adding "meeting" so we can discuss this sometime. I am fine with this not having any particular alpha/beta designation, but if you think it should be for one of the milestones, go ahead and label it as such. Thanks.

**Comment by gwhitney** [comment]
This issue (or at least many instances of it, including the ones specifically mentioned here) is fixed in ui2, so closing.
