### ISSUE TITLE
visual design of sequence selection box when few sequences

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#479]
When there are very few sequences, we see stretched boxes in the selector (ui2), as in the attached screenshot.  Do we want this?
![Screenshot from 2024-10-27 14-34-02](https://github.com/user-attachments/assets/32473ec1-6c64-49fe-874a-2a8412a8c27c)

**Comment by gwhitney** [comment]
No, we definitely do not. May be a CSS problem. Definitely a bug in the new ui. Slating for alpha.

**Comment by gwhitney** [comment]
Implemented in ui2 per #495, closing.
