### ISSUE TITLE
What do we want clicks on the numberscope logo at top left to do?

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#483]
The intention of the code in Scope.vue and NavBar.vue on the behavior of the numberscope logo is very muddled.

Some code seems to imply it should act just like the "replay" button in the specimen bar (with the circle arrow, to the left of the play/pause button). That seems redundant. I believe that's what is happening in ui2.

Some code seems to imply it should go back to the current visualizer at the time that this visualization was first loaded (i.e., ignoring any other visualizers you might have visited without navigating away from the Scope view since then). That is a distinct behavior, but it doesn't seem very intuitive or useful to me. The same effect could be obtained by hitting the back button some number of times (although the browser history of different visualizations can get very long, so I guess there is some utility for a "take me back to the beginning" button -- it's just that what constitutes the "beginning" is very contingent. For example, if you go to the gallery and click a specimen there to go back to the Scope, that specimen becomes the new beginning. Similarly if you go a documentation page and then click the back button -- whatever visualization you were on becomes the new beginning.) 

The changes to respect the back button that I am working on have the side effect of tipping which of these two bits of code wins out, so it will change the behavior of clicking on the numberscope logo to the second, "back to the beginning" behavior.

Personally, I would expect the logo to go to the "project homepage", whatever that is. We used to have a splash page, and then the logo went to that splash page. But we've dropped the splash page...

One idea would be for it to take you to the "About" page in the documentation, and then we could just remove the About entry from the menu at top right.

Anyhow, what should it do?

**Comment by katestange** [comment]
Yeah I feel like it should take you to About or some "home page about the project" (of which I guess About is the closest).  We don't need "About" at the right, if we are taking out clutter, since you could certainly also click "Documentation" to eventuallly get to "About" if you are really looking for that and don't think to click the logo.

**Comment by katestange** [comment]
Also, going back to "start of scope" doesn't seem particularly useful.
