### ISSUE TITLE
Visualizers should call checkParameters when sequence changes

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#487]
Like the testing issues, the documentation issues are great for surfacing underlying problems. Responsive to #46, I am designing a "visualizer lifecycle diagram" (along the lines of the [Vue component lifecycle](https://vuejs.org/guide/essentials/lifecycle.html#lifecycle-diagram) diagram). That exercise has uncovered the following inconsistency:

* We document the checkParameters() method of a (P5)Visualizer as being able to rely on, and use, the sequence `.first` and `.last` properties in validating the parameters of the visualizer, and indeed, some of our Visualizer classes (e.g. Turtle) do so. Yet when the sequence changes, the update pathway only goes back to presketch(); if no parameters specific to the visualizer have changed, the visualizer checkParameters() is not called again. So whatever validations were done on the sequence extents may now be in a failed state. This mismatch is even called out as a bug in the comments in Turtle.ts.

Should we modify the update pathway on sequence change for a Visualizer to include calling checkParameters()? Or if not, how should the above inconsistency be resolved? I do not think the inconsistency should be allowed to remain.

**Comment by katestange** [comment]
Is there any reason not to modify the update pathway as you suggest?

**Comment by gwhitney** [comment]
I can't think of any reason other than it's yet another change and will have various repercussions we need to track down and likely fix. But in the long run, it definitely seems like a better scheme. So we could just go for it now while everything is in turmoil anyway ;-)

**Comment by katestange** [comment]
Sounds like updating the pathway makes sense then?

**Comment by gwhitney** [comment]
OK, renamed the issue accordingly.

**Comment by gwhitney** [comment]
Implemented in ui2 by #486. Closing.
