### ISSUE TITLE
testing sequence caching

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#54]
Once the test framework is up and running, there should be a test that the caching of sequences (SequenceCached.ts) never calls calculate() twice for the same index n.  The random integer sequence functionality (PR #53) relies on this guarantee, since we wish to guarantee that the randomly generated value is the same if the same term is called twice.  But its calculate() function is just a call to Random(), so without careful caching, this guarantee would not be met.

**Comment by gwhitney** [comment]
Depends on resolution of #25. (Does Github have formal dependencies among issues/PRs? Some repository packages do...)

**Comment by gwhitney** [comment]
This should be folded into #420. Adding milestone.

**Comment by gwhitney** [comment]
Completed in ui2 thanks to #420. Closing.
