### ISSUE TITLE
framework is silent when Visualizers throw an exception

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#63]
Right now if a Visualizer has a bug in it or encounters some unexpected condition that causes an exception to be thrown, terminating its operation, the frontscope just silently does nothing. This presents a bad image to the visitor, that it just doesn't work or has hung or something. The framewok ought to put a high-level "catch" around the invocation of any Visualizer so at least it can try to report the problem -- maybe the visitor will be able to tell what's wrong. And at least "sorry, I encountered a problem with that Visualizer" is better than silent inactivity (even if it's still quite bad, it's not as terrible a user experience).

**Comment by liammulh** [comment]
Vue has an [error handler](https://vuejs.org/api/application.html#app-config-errorhandler).

> It can capture errors from the following sources:
> - Component renders
> - Event handlers
> - Lifecycle hooks
> - setup() function
> - Watchers
> - Custom directive hooks
> - Transition hooks

So it isn't going to catch everything.

There's also the [warn handler](https://vuejs.org/api/application.html#app-config-warnhandler).
