### ISSUE TITLE
Refactor Code to Use async/await

### ISSUE THREAD

**Issue by liam-mulhall** [numberscope/frontscope#70]
There are plenty of instances of old promise syntax throughout the code base. This is the old way of doing asynchronous JS. It's harder to read than the new async/await syntax. We should be getting rid of the promise syntax and using async/await as we move forward.

If you aren't familiar with the various ways to do asynchronous JS, check out [this excellent blog](https://medium.com/front-end-weekly/callbacks-promises-and-async-await-ad4756e01d90). It does a good job of summarizing the evolution of asynchronous JS.

**Comment by gwhitney** [comment]
> plenty of instances

I grepped for "then" and found it in SequencePlayground.vue and OEISSequenceTemplate.ts. The former I will eliminate from the codebase per #33 (it has a hardcoded URL in it, so isn't very functional anyway), and the latter I can address in a PR for this issue. But did you see other instances of asynchronous calls that should be handled with async/await? If you can point me to them, I will address.

**Comment by liam-mulhall** [comment]
I think my “plenty” comment may have just been faulty memory. I'm willing to bet that grep is more accurate than my memory.
