### ISSUE TITLE
TurtleVisualizer silently fails on out-of-range data

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#76]
To reproduce: Start Numberscope, select Random sequence with default parameters, select Turtle Graphics with default parameters, and Create Bundle. Nothing is drawn and no feedback is provided.

**Comment by liammulh** [comment]
Related to https://github.com/numberscope/frontscope/issues/63.

**Comment by liammulh** [comment]
@gwhitney, I can't reproduce following your steps. https://github.com/numberscope/frontscope/pull/185 might fix this, but I can't tell because I can't repro.

**Comment by gwhitney** [comment]
Yeah, you might get something depending on the random numbers, but quickly it just silently stops. Turns out this (non-)behavior is exactly coded in the current Turtle, and might be moot/go away when Turtle is replaced.

**Comment by gwhitney** [comment]
Should be addressed in the in-progress Turtle overhaul (#402). Setting milestone.

**Comment by gwhitney** [comment]
Resolved by #404. Closing.
