### ISSUE TITLE
Create an (interesting) "Specimens" page.

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#78]
This would be the destination of ~~Both @gwhitney and I don't understand~~ the "Specimens" button (which should maybe be renamed something like "Interesting Specimens"?

**Comment by katestange** [comment]
The idea was to have a page where we have presets to cool visualizations.  These would be thumbnails, curated, like a gallery.  Like a library of specimens (like microscope slides) that have been collected to use in the scope, see?  :)  But yeah, if it's not so clear what it means, it may not be a useful button.  Anyway, that's what it was.

**Comment by gwhitney** [comment]
Seems like a plausible feature to me, so changing this issue to request its implementation.

**Comment by gwhitney** [comment]
This is implemented by the Gallery in ui2, so closing.
