### ISSUE TITLE
In NavBar, logo should go to home page and "The Scope" should go to the main tool

### ISSUE THREAD

**Issue by gwhitney** [numberscope/frontscope#81]
Right now they both go to the home page, which seems redundant, and means that there isn't a nice correspondence between the nav bar buttons and the main available routes. (Ignoring the fact that "Specimens" is not yet implemented, see #78.)

**Comment by liam-mulhall** [comment]
This is done in https://github.com/numberscope/frontscope/pull/123.

**Comment by gwhitney** [comment]
Check, closing.
