### ISSUE TITLE
Create ability to import/Export settings for seq and viz via JSON

### ISSUE THREAD

**Issue by khaledallen** [numberscope/frontscope#83]
[extracted from todo.md]

The request here is that a particular combination of visualizer + sequence + settings for both can be saved and exported/imported via some protocol (JSON is probably the best bet), so that it can later be shared with someone else who also has access to the numberscope.

Excluded from this request is shareability of visualizers and/or sequences. I believe the idea was that anyone who can access our official instance of numberscope can share these JSONs with others who also have access, to essentially share the visualization in a more useful way than just an image.

**Comment by gwhitney** [comment]
This is implemented in ui2 via URLs. Closing.
