### ISSUE TITLE
Add `pre-commit` Hook That Lints and Auto-Formats Files

### ISSUE THREAD

**Issue by liam-mulhall** [numberscope/frontscope#96]
Once https://github.com/numberscope/frontscope/pull/90 is merged, we'll want a `pre-commit` hook that lints and auto-formats files so that a developer doesn't forget to lint and format. There is a nice package that can install Git hooks for you: https://github.com/typicode/husky.

**Comment by liam-mulhall** [comment]
This is done in https://github.com/numberscope/frontscope/pull/123.

**Comment by gwhitney** [comment]
Check, closing.
